### PR TITLE
add proxy support

### PR DESCRIPTION
**Pull request by LiuBiCai**
The Recaptcha and funcaptcha usually need proxy to solve. So I need the proxy support to do that.

### CODE REVIEW

**Comment by Zaczero** [comment]
Thank you for your contribution. I'll test your changes and possibly commit them in the near future.

**Comment by 0x178F** [comment]
hi, i have a problem :(  how to fix?
Screenshot_10

**Comment by Zaczero** [comment]
> 
> 
> hi, i have a problem :( how to fix?
> Screenshot_10

Hey, make it _2Captcha._2Captcha(..)
I'll most likely change it for the future releases.

**Comment by LiuBiCai** [comment]
> hi, i have a problem :( how to fix?
> 
> 
> Hey, make it _2Captcha._2Captcha(..)
> I'll most likely change it for the future releases.

The namespace and class used the same name which's not a good idea. Maybe change that will well.

**Review by Zaczero — APPROVED** [review]
Everything looks good

**Pull request merged**
